apiVersion: v1
entries:
  azdo-demand-agent:
  - apiVersion: v2
    created: "2021-03-19T00:33:25.915956-04:00"
    description: A Helm chart for On Demand Agents - Demand agent
    digest: b2966bcc30237c73372cf891090c4fb6f5ace18dce88301a7fdfd03867263f44
    name: azdo-demand-agent
    type: application
    urls:
    - azdo-demand-agent-0.1.0.tgz
    version: 0.1.0
  azdo-init-agent:
  - apiVersion: v2
    created: "2021-03-19T00:33:25.916871-04:00"
    description: A Helm chart for On Demand Agents - INIT agent
    digest: 6650a4858c6f2b71db47122bf395192b27246d01d5cea304b2b859cd4d64a662
    name: azdo-init-agent
    type: application
    urls:
    - azdo-init-agent-0.1.0.tgz
    version: 0.1.0
generated: "2021-03-19T00:33:25.915427-04:00"
