# Azure DevOps baseimage (../Dockerfile-baseimage)
# More info: https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops#create-and-build-the-dockerfile-1
FROM agiletrailblazers/azdo-agent:latest

RUN curl -sL https://deb.nodesource.com/setup_10.x | bash - && \
    apt-get install -y nodejs && apt-get install wget && apt-get install unzip

RUN apt-get update && apt-get install -y python-pip
#RUN pip install ansible

RUN whoami

# install default maven
RUN apt-get install -y -f git-core && git --version
#RUN apt-get install -y maven && mvn --version
RUN apt-get install default-jre

# install maven 3.6.3
#RUN wget http://www-eu.apache.org/dist/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
#RUN tar -C /usr/share/ -xvzf apache-maven-3.6.3-bin.tar.gz
#RUN /usr/share/apache-maven-3.6.3/bin/mvn --version

# install gradle 5
#RUN wget https://services.gradle.org/distributions/gradle-5.0-bin.zip -P /tmp
#RUN unzip -d /opt/gradle /tmp/gradle-*.zip

# install gradle 6
#RUN wget https://services.gradle.org/distributions/gradle-6.0-bin.zip -P /tmp
#RUN unzip -d /opt/gradle /tmp/gradle-6.0*.zip

###Install sonarscanner binary#####
RUN wget https://repo1.maven.org/maven2/org/sonarsource/scanner/cli/sonar-scanner-cli/4.6.0.2311/sonar-scanner-cli-4.6.0.2311.zip -P /tmp
RUN unzip -d /opt /tmp/sonar-scanner-cli-4.6.*.zip
RUN /opt/sonar-scanner-4.6.0.2311/bin/sonar-scanner --version

### Install node,npm and protractor ####
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash -
RUN apt-get install -y nodejs
RUN node -v && npm -v && npm install -g protractor
RUN protractor --version

### Install spin cli ###
RUN curl -LO https://storage.googleapis.com/spinnaker-artifacts/spin/$(curl -s https://storage.googleapis.com/spinnaker-artifacts/spin/latest)/linux/amd64/spin
RUN chmod +x spin
#RUN chown jenkins:jenkins spin
RUN mv spin /usr/local/bin/spin

### Install chromedriver ###
RUN wget https://chromedriver.storage.googleapis.com/79.0.3945.36/chromedriver_linux64.zip -P /tmp
RUN unzip -d /usr/local/bin /tmp/chromedriver_linux64.zip
RUN apt-get install -y libx11-dev
RUN chromedriver -v

### Install cucumber ###
RUN apt-get install -y cucumber

### Install JQ ###
RUN apt-get install -y jq
RUN apt-get install -y xvfb
RUN pip install requests

### Install groovy
RUN apt-get install -y groovy

### Install anchore-cli
RUN pip install anchorecli
RUN export PATH="$HOME/.local/bin/:$PATH"

#USER azdo
# Spinnaker Config
RUN spin --version
RUN mkdir /home/azdo
RUN mkdir /home/azdo/.spin/
ADD config /home/azdo/.spin/

USER root
# Export environment variables for gradle
ENV GRADLE_HOME=/opt/gradle/gradle-6.0
ENV SONAR_SCANNER_HOME=/opt/sonar-scanner-4.2.0.1873
ENV PATH=$PATH:$GRADLE_HOME/bin:$SONAR_SCANNER_HOME/bin
RUN gradle -v
RUN sonar-scanner --version
