kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jira-node1-pv-claim
  labels:
    app: jira
spec:
  storageClassName: nfs-atlassian-np
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jira-node2-pv-claim
  labels:
    app: jira
spec:
  storageClassName: nfs-atlassian-np
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jira-shared-home-pv-claim
  labels:
    app: jira
spec:
  storageClassName: nfs-atlassian-np
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi