apiVersion: v1    # confluence Deployment for node 1
kind: Pod
metadata:
  labels:
    app: confluence
  name: confluence-node1
spec:
  restartPolicy: Always
  containers:
    - name: confluence-node1
      image: "agiletrailblazers/confluence-server:7.3.3"
      ports:
        - containerPort: 8090
      env:
        - name: ATL_PRODUCT_HOME_SHARED
          value: "/var/atlassian/application-data/confluence/shared-home"
        - name: ATL_CLUSTER_NAME
          value: "Confluence Cluster"
        - name: ATL_CLUSTER_TYPE
          value: "tcp_ip"
        - name: ATL_CLUSTER_NODE_NAME
          value: "confluence-node1"
        - name: ATL_TOMCAT_SECURE
          value: "true"
        - name: ATL_TOMCAT_SCHEME
          value: "https"
        - name: ATL_PROXY_PORT
          value:  "443"
        - name: ATL_PROXY_NAME
          value:  "confluence.agiletrailblazers.com"
        - name: JVM_MINIMUM_MEMORY
          value:  "2048m"
        - name: JVM_MAXIMUM_MEMORY
          value:  "4096m"
      resources:
        limits:
          cpu: "4"
          memory: "8G"
        requests:
          cpu: "2"
          memory: "2G"
      volumeMounts:
        - name: "confluence-home"
          mountPath: /var/atlassian/application-data/confluence
        - name: "confluence-shared-home"
          mountPath: /var/atlassian/application-data/confluence/shared-home
  volumes:
    - name: confluence-home
      persistentVolumeClaim:
        claimName: confluence-home-node1-pv-claim
    - name: confluence-shared-home
      persistentVolumeClaim:
        claimName: confluence-shared-home-pv-claim
---           #Provide authorization for confluence
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: confluence-k8-calls
subjects:
  - kind: ServiceAccount
    # Reference to upper's `metadata.name`
    name: default
    # Reference to upper's `metadata.namespace`
    namespace: confluence
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
