apiVersion: v1                           # Jira Deployment Node 2
kind: Pod
metadata:
  labels:
    app: jira
  name: jira-node2
spec:
  containers:
    - name: jira-node2
      image: "agiletrailblazers/jira-software:9.5.0.2"
      ports:
        - containerPort: 8080
        - containerPort: 40001
      env:
      - name: CLUSTERED
        value: "true"
      - name: JIRA_NODE_ID
        value:  "jira-node2"
      - name: ATL_TOMCAT_SECURE
        value: "true"
      - name: ATL_TOMCAT_SCHEME
        value: "https"
      - name: ATL_PROXY_PORT
        value:  "443"
      - name: ATL_PROXY_NAME
        value:  "jira.agiletrailblazers.com"
      - name: JVM_SUPPORT_RECOMMENDED_ARGS
        value:  "-Datlassian.plugins.enable.wait=300"
      - name: JVM_MINIMUM_MEMORY
        value:  "1024m"
      - name: JVM_MAXIMUM_MEMORY
        value:  "4096m"
      resources:
        limits:
          cpu: "4"
          memory: "16G"
        requests:
          cpu: "2"
          memory: "8G"
      volumeMounts:
        - name: "jira-home"
          mountPath: /var/atlassian/application-data/jira
        - name: "jira-shared-home"
          mountPath: /var/atlassian/application-data/jira/shared
  volumes:
    - name: jira-home
      persistentVolumeClaim:
        claimName: jira-home-node2-pv-claim
    - name: jira-shared-home
      persistentVolumeClaim:
        claimName: jira-shared-home-pv-claim
